sudo: false
language: python
python:
  - "2.7"

addons:
  apt:
    packages:
      - lcov

install:
  - pip install -U pip wheel codecov
  - pip install -r requirements.txt
  - python setup.py develop

script:
  - ./test.sh

after_success:
  - codecov

deploy:
  provider: pypi
  user: edx
  password:
    secure: vq1P/q8v0doD55DGSvL8geAo4+ADz71kqCQJeZcXLfX3ICWAbW/l7eKpJNcp3wE7j2T45QpTp8L84PAL71Lh9gQho0R3mH3kDFTESn/03PSJAfjyuOMLRP+cCKE5UZ5FVg3vA3ZZRN2qHFX+5WlalbZjQgPf1HMX9n3YDdiWg0I=
  distributions: sdist bdist_wheel
  on:
    tags: true
