sudo: false
language: python
python:
  - "2.7"

addons:
  apt:
    packages:
      - lcov

install:
  - pip install -U pip wheel codecov
  - make requirements

script:
  - make test

after_success:
  - codecov

deploy:
  provider: pypi
  user: edx
  password:
    secure: LQX5TSthhGHnFivDc67/O5PNFyrxH3Ch5u9sJmBtjHE2q0HHBk4JP7m7WYbTUiKJlFMR+Q6TdXRp7f64PdGKfEi3teeTUCHUkgkRzBwF832MHqCRmA/FmD0U9pmTrV7iIaid+GbFE4pnfeKvtQievZfJxAm9y7ExT3bcztNYlSQ=
  distributions: sdist bdist_wheel
  on:
    tags: true
