sudo: false
language: python
python:
  - "2.7"

addons:
  apt:
    packages:
      - lcov

install:
  - pip install -U pip wheel codecov
  - pip install -r requirements.txt
  - python setup.py develop

script:
  - ./test.sh

after_success:
  - codecov
