sudo: false
language: python
python:
  - "2.7"

addons:
  apt:
    packages:
      - lcov

install:
  - pip install -U pip wheel codecov
  - make requirements

script:
  - make test

after_success:
  - codecov

deploy:
  provider: pypi
  user: edx
  password:
    secure: F0Nw61+R0HX8wbSTDm/iskxb/FHHP4H5sxaPmT8ZC6W/ojz726KHU0dyW5yu4PSf/xbnAnbpdLSx7NS8k3uNMiK6a6T0VvMSYySOz7yjh1O+zrzNrZTkyrQ9QA68D1W96PRP+xjhfxQC18A2B8niahig4ZLNBlkdKNnm36rS96g=
  distributions: sdist bdist_wheel
  on:
    tags: true
