# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-04 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth2', '0002_auto_20180712_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_type',
            field=models.IntegerField(choices=[(0, 'Confidential (Web applications)'), (1, 'Public (Native and JS applications)'), (2, 'Auto Generated applications by the web app')]),
        ),
        migrations.AlterField(
            model_name='client',
            name='redirect_uri',
            field=models.URLField(help_text="Your application's callback URL"),
        ),
        migrations.AlterField(
            model_name='client',
            name='url',
            field=models.URLField(help_text="Your application's URL."),
        ),
        migrations.AlterField(
            model_name='scope',
            name='description',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
